# Конфигурация проекта Serena для zamer
# Индексируются только папки: models, container

# Языки для языкового сервера
languages:
- python

# Кодировка файлов
encoding: "utf-8"

# Использовать gitignore
ignore_all_files_in_gitignore: true

# Исключённые пути - всё кроме models и container
# Используем синтаксис gitignore
ignored_paths:
- docs/
- dont-know/
- scripts/
- .claude/
- .vscode/

# Проект не в режиме только для чтения
read_only: false

# Исключённые инструменты (пусто - все доступны)
excluded_tools: []

# Начальный промпт
initial_prompt: ""

# Имя проекта
project_name: "zamer"

# Опциональные инструменты
included_optional_tools: []
