# Конфигурация проекта Serena для zamer
# Индексируются только папки: models, container

# Языки для языкового сервера
languages:
- python

# the encoding used by text files in the project
# For a list of possible encodings, see https://docs.python.org/3.11/library/codecs.html#standard-encodings
encoding: "utf-8"

# Использовать gitignore
ignore_all_files_in_gitignore: true

# Исключённые пути - всё кроме models и container
# Используем синтаксис gitignore
ignored_paths:
- docs/
- dont-know/
- scripts/
- .claude/
- .vscode/

# whether the project is in read-only mode
# If set to true, all editing tools will be disabled and attempts to use them will result in an error
# Added on 2025-04-18
read_only: false

# Исключённые инструменты (пусто - все доступны)
excluded_tools: []

# Начальный промпт
initial_prompt: ""

# Имя проекта
project_name: "zamer"

# Опциональные инструменты
included_optional_tools: []

# list of mode names to that are always to be included in the set of active modes
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the base_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this setting overrides the global configuration.
# Set this to [] to disable base modes for this project.
# Set this to a list of mode names to always include the respective modes for this project.
base_modes:

# list of mode names that are to be activated by default.
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the default_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this overrides the setting from the global configuration (serena_config.yml).
# This setting can, in turn, be overridden by CLI parameters (--mode).
default_modes:

# fixed set of tools to use as the base tool set (if non-empty), replacing Serena's default set of tools.
# This cannot be combined with non-empty excluded_tools or included_optional_tools.
fixed_tools: []
